package net.pokereport.luna.cosmetics;

import java.util.List;

import net.pokereport.luna.cosmetics.Catalogo.Pieza;

/**
 * Los sombreros que lleva el JUGADOR.
 *
 * <p><b>ESTE FICHERO SE GENERA:</b> {@code python tools/gen_catalogo_cosmeticos.py}
 *
 * <p>Se genera <b>leyendo los packs</b>, que es lo unico que dice la verdad sobre
 * lo que se puede dibujar. Escribirlo a mano fallo tres veces, y las tres se
 * cobro un cosmetico que no se veia. Ver la cabecera del generador.
 *
 * <p>⚠ Los precios son por tramos y <b>PROVISIONALES</b>.
 */
public final class CatalogoSombreros {

    private CatalogoSombreros() {
    }

    static final List<Pieza> PIEZAS = List.of(
            new Pieza("sombrero_acornhat", Catalogo.SOMBREROS, "", "Acorn Cap", 1200),
            new Pieza("sombrero_aegishat", Catalogo.SOMBREROS, "", "Aegis", 1200),
            new Pieza("sombrero_alien_antennae", Catalogo.SOMBREROS, "", "Alien Antennae", 1200),
            new Pieza("sombrero_alienphil", Catalogo.SOMBREROS, "", "Phil?", 1200),
            new Pieza("sombrero_alolan_digglethat", Catalogo.SOMBREROS, "", "Alolan digglethat", 1200),
            new Pieza("sombrero_amalgalichhat", Catalogo.SOMBREROS, "", "Amalgalich", 1200),
            new Pieza("sombrero_ampharos", Catalogo.SOMBREROS, "", "Ampharos", 1200),
            new Pieza("sombrero_ampharos_shiny", Catalogo.SOMBREROS, "", "Ampharos shiny", 1200),
            new Pieza("sombrero_angel_and_devil", Catalogo.SOMBREROS, "", "Angel and Devil", 1200),
            new Pieza("sombrero_angrymask", Catalogo.SOMBREROS, "", "Tribal Mask", 1200),
            new Pieza("sombrero_antlers", Catalogo.SOMBREROS, "", "Antlers", 1200),
            new Pieza("sombrero_apple", Catalogo.SOMBREROS, "", "Apple", 1200),
            new Pieza("sombrero_applinhat", Catalogo.SOMBREROS, "", "Applinhat", 1200),
            new Pieza("sombrero_applinhat_shiny", Catalogo.SOMBREROS, "", "Applinhat shiny", 1200),
            new Pieza("sombrero_artsy", Catalogo.SOMBREROS, "", "Artsy", 1200),
            new Pieza("sombrero_artsy_doll", Catalogo.SOMBREROS, "", "Artsy Doll", 1200),
            new Pieza("sombrero_ash_journey", Catalogo.SOMBREROS, "", "Ash journey", 1200),
            new Pieza("sombrero_astronaut", Catalogo.SOMBREROS, "", "Astronaut", 1200),
            new Pieza("sombrero_axolotl_on_head", Catalogo.SOMBREROS, "", "Axolotl Friend", 1200),
            new Pieza("sombrero_azumanga_hat", Catalogo.SOMBREROS, "", "Azumanga's Hat", 1200),
            new Pieza("sombrero_baby_crewmate", Catalogo.SOMBREROS, "", "Baby Crewmate", 1200),
            new Pieza("sombrero_babydolphin", Catalogo.SOMBREROS, "", "Baby Dolphin", 1200),
            new Pieza("sombrero_babyturtle", Catalogo.SOMBREROS, "", "Baby Turtle", 1200),
            new Pieza("sombrero_bandana", Catalogo.SOMBREROS, "", "Bandana", 1200),
            new Pieza("sombrero_bandanargb", Catalogo.SOMBREROS, "", "RGB Bandana", 1200),
            new Pieza("sombrero_baseballeaster", Catalogo.SOMBREROS, "", "Easter Baseball Cap", 1200),
            new Pieza("sombrero_baseballhat", Catalogo.SOMBREROS, "", "Baseball Cap", 1200),
            new Pieza("sombrero_baseballhatfestive", Catalogo.SOMBREROS, "", "Festive Baseball Cap", 1200),
            new Pieza("sombrero_baseballhatjuly", Catalogo.SOMBREROS, "", "Summer Baseball Cap", 1200),
            new Pieza("sombrero_baseballhatrgb", Catalogo.SOMBREROS, "", "RGB Baseball Cap", 1200),
            new Pieza("sombrero_batwinghat", Catalogo.SOMBREROS, "", "Bat Wing Hat", 1200),
            new Pieza("sombrero_beanie", Catalogo.SOMBREROS, "", "Beanie", 1200),
            new Pieza("sombrero_beanieeaster", Catalogo.SOMBREROS, "", "Easter Beanie", 1200),
            new Pieza("sombrero_beaniefestive", Catalogo.SOMBREROS, "", "Festive Beanie", 1200),
            new Pieza("sombrero_beaniejuly", Catalogo.SOMBREROS, "", "Summer Beanie", 1200),
            new Pieza("sombrero_beaniergb", Catalogo.SOMBREROS, "", "RGB Beanie", 1200),
            new Pieza("sombrero_beaniespooky", Catalogo.SOMBREROS, "", "Halloween Beanie", 1200),
            new Pieza("sombrero_bee_on_head", Catalogo.SOMBREROS, "", "Bee Friend", 1200),
            new Pieza("sombrero_beehat", Catalogo.SOMBREROS, "", "Bee Hat", 1200),
            new Pieza("sombrero_beehatpride", Catalogo.SOMBREROS, "", "Beehatpride", 1200),
            new Pieza("sombrero_beehattrans", Catalogo.SOMBREROS, "", "Beehattrans", 1200),
            new Pieza("sombrero_beetle_on_head", Catalogo.SOMBREROS, "", "Beetle Friend", 1200),
            new Pieza("sombrero_beret_ribbon", Catalogo.SOMBREROS, "", "Beret Ribbon", 1200),
            new Pieza("sombrero_bicorne", Catalogo.SOMBREROS, "", "Bicorne", 1200),
            new Pieza("sombrero_bigbrain", Catalogo.SOMBREROS, "", "Big Brain", 1200),
            new Pieza("sombrero_bigcrown", Catalogo.SOMBREROS, "", "Big Crown", 1200),
            new Pieza("sombrero_bigeyes", Catalogo.SOMBREROS, "", "Big Eyes", 1200),
            new Pieza("sombrero_bigribbon", Catalogo.SOMBREROS, "", "Big Ribbon", 1200),
            new Pieza("sombrero_bigstevehead", Catalogo.SOMBREROS, "", "Mascot Head", 1200),
            new Pieza("sombrero_binky", Catalogo.SOMBREROS, "", "Binky", 1200),
            new Pieza("sombrero_blaziken_cap", Catalogo.SOMBREROS, "", "Blaziken cap", 1200),
            new Pieza("sombrero_blaziken_cap_shiny", Catalogo.SOMBREROS, "", "Blaziken cap shiny", 1200),
            new Pieza("sombrero_bluefireeye", Catalogo.SOMBREROS, "", "Skeleton Eye", 1200),
            new Pieza("sombrero_bowler", Catalogo.SOMBREROS, "", "Bowler Cap", 1200),
            new Pieza("sombrero_breadhat", Catalogo.SOMBREROS, "", "Bread on Head", 1200),
            new Pieza("sombrero_breloomshroom", Catalogo.SOMBREROS, "", "Breloomshroom", 1200),
            new Pieza("sombrero_breloomshroom_shiny", Catalogo.SOMBREROS, "", "Breloomshroom shiny", 1200),
            new Pieza("sombrero_brownbrick", Catalogo.SOMBREROS, "", "Brick on Head", 1200),
            new Pieza("sombrero_bucket", Catalogo.SOMBREROS, "", "Bucket", 1200),
            new Pieza("sombrero_buneary", Catalogo.SOMBREROS, "", "Buneary", 1200),
            new Pieza("sombrero_buneary_shiny", Catalogo.SOMBREROS, "", "Buneary shiny", 1200),
            new Pieza("sombrero_bunnyhat", Catalogo.SOMBREROS, "", "Bunny Hat", 1200),
            new Pieza("sombrero_burgerhat", Catalogo.SOMBREROS, "", "Burger", 1200),
            new Pieza("sombrero_burning_m_bison", Catalogo.SOMBREROS, "", "Burning Flames Team Captain", 1200),
            new Pieza("sombrero_caddycap", Catalogo.SOMBREROS, "", "Caddy Cap", 1200),
            new Pieza("sombrero_camera", Catalogo.SOMBREROS, "", "Camera Head", 1200),
            new Pieza("sombrero_camerabeard", Catalogo.SOMBREROS, "", "Camera Beard", 1200),
            new Pieza("sombrero_candleonhead", Catalogo.SOMBREROS, "", "Candle", 1200),
            new Pieza("sombrero_candycane", Catalogo.SOMBREROS, "", "Candy Cane", 1200),
            new Pieza("sombrero_capbackwards", Catalogo.SOMBREROS, "", "Capbackwards", 1200),
            new Pieza("sombrero_cardboard_box", Catalogo.SOMBREROS, "", "Cardboard Box", 1200),
            new Pieza("sombrero_carrotonstick", Catalogo.SOMBREROS, "", "Carrot on a Stick", 1200),
            new Pieza("sombrero_cartoonegg", Catalogo.SOMBREROS, "", "Cartoon Egg", 1200),
            new Pieza("sombrero_cat_hat", Catalogo.SOMBREROS, "", "Cat Hat", 1200),
            new Pieza("sombrero_cat_on_head", Catalogo.SOMBREROS, "", "Cat Friend", 1200),
            new Pieza("sombrero_caterpillar_on_head", Catalogo.SOMBREROS, "", "Caterpillar Friend", 1200),
            new Pieza("sombrero_chalk_stick", Catalogo.SOMBREROS, "", "Chalk Stick", 1200),
            new Pieza("sombrero_cheeseslice", Catalogo.SOMBREROS, "", "Cheese Slice", 1200),
            new Pieza("sombrero_chefshat", Catalogo.SOMBREROS, "", "Chef's Hat", 1200),
            new Pieza("sombrero_chi_ears", Catalogo.SOMBREROS, "", "Chi's Ears", 1200),
            new Pieza("sombrero_chickenhead", Catalogo.SOMBREROS, "", "Chicken Head", 1200),
            new Pieza("sombrero_chickenonhead", Catalogo.SOMBREROS, "", "Chicken on Head", 1200),
            new Pieza("sombrero_chocolate_sauced", Catalogo.SOMBREROS, "", "Chocolate Sauced", 1200),
            new Pieza("sombrero_christmascakehat", Catalogo.SOMBREROS, "", "Fruit Cake", 1200),
            new Pieza("sombrero_christmastree", Catalogo.SOMBREROS, "", "Festive Tree", 1200),
            new Pieza("sombrero_circular_glasses", Catalogo.SOMBREROS, "", "Circular Glasses", 1200),
            new Pieza("sombrero_clockface", Catalogo.SOMBREROS, "", "Clock Head", 1200),
            new Pieza("sombrero_cowboy", Catalogo.SOMBREROS, "", "Cowboy Hat", 1200),
            new Pieza("sombrero_cowboyrgb", Catalogo.SOMBREROS, "", "RGB Cowboy Hat", 1200),
            new Pieza("sombrero_crabonhead", Catalogo.SOMBREROS, "", "Crab on Head", 1200),
            new Pieza("sombrero_crown", Catalogo.SOMBREROS, "", "Crown", 1200),
            new Pieza("sombrero_crystal_horns", Catalogo.SOMBREROS, "", "Crystal Horns", 1200),
            new Pieza("sombrero_cucumbereyemask", Catalogo.SOMBREROS, "", "Cucumber Eye Mask", 1200),
            new Pieza("sombrero_cuphead", Catalogo.SOMBREROS, "", "Cup Head", 1200),
            new Pieza("sombrero_cyclopseye", Catalogo.SOMBREROS, "", "Cyclops Eye", 1200),
            new Pieza("sombrero_dairyqueen", Catalogo.SOMBREROS, "", "DQ Lips", 1200),
            new Pieza("sombrero_dangereqsue", Catalogo.SOMBREROS, "", "Dangeresque Shades", 1200),
            new Pieza("sombrero_dangeresquejuly", Catalogo.SOMBREROS, "", "Summer Dangeresque Shades", 1200),
            new Pieza("sombrero_dawn_hat", Catalogo.SOMBREROS, "", "Dawn hat", 1200),
            new Pieza("sombrero_dejiko", Catalogo.SOMBREROS, "", "Dejiko's Hat", 1200),
            new Pieza("sombrero_demoneyes", Catalogo.SOMBREROS, "", "Demon Eyes", 1200),
            new Pieza("sombrero_demonhorns", Catalogo.SOMBREROS, "", "Demon Horns", 1200),
            new Pieza("sombrero_digger", Catalogo.SOMBREROS, "", "Diglett", 1200),
            new Pieza("sombrero_digglethat", Catalogo.SOMBREROS, "", "Digglethat", 1200),
            new Pieza("sombrero_digglethat_shiny", Catalogo.SOMBREROS, "", "Digglethat shiny", 1200),
            new Pieza("sombrero_dimmahat", Catalogo.SOMBREROS, "", "Dimmadome Dimmahat", 1200),
            new Pieza("sombrero_dipper", Catalogo.SOMBREROS, "", "Dipper", 1200),
            new Pieza("sombrero_discoball", Catalogo.SOMBREROS, "", "Disco", 1200),
            new Pieza("sombrero_disguise", Catalogo.SOMBREROS, "", "Disguise", 1200),
            new Pieza("sombrero_doctorhat", Catalogo.SOMBREROS, "", "Doctor's Gear", 1200),
            new Pieza("sombrero_dorkglassesandteeth", Catalogo.SOMBREROS, "", "Dork", 1200),
            new Pieza("sombrero_doubletake", Catalogo.SOMBREROS, "", "Double Take", 1200),
            new Pieza("sombrero_dragonhead", Catalogo.SOMBREROS, "", "Dragon Head", 1200),
            new Pieza("sombrero_dragonskull", Catalogo.SOMBREROS, "", "Dragon Skull", 1200),
            new Pieza("sombrero_dragonskullender", Catalogo.SOMBREROS, "", "Ender Dragon Skull", 1200),
            new Pieza("sombrero_drinkinhat", Catalogo.SOMBREROS, "", "Drinking Hat", 1200),
            new Pieza("sombrero_druid_antlers", Catalogo.SOMBREROS, "", "Druid Antlers", 1200),
            new Pieza("sombrero_druid_antlers_rare", Catalogo.SOMBREROS, "", "Elder Druid Antlers", 1200),
            new Pieza("sombrero_dumhat", Catalogo.SOMBREROS, "", "Dum", 1200),
            new Pieza("sombrero_dwarfbeard", Catalogo.SOMBREROS, "", "Dwarfbeard", 1200),
            new Pieza("sombrero_dwarfminerbeard", Catalogo.SOMBREROS, "", "Dwarven Miner", 1200),
            new Pieza("sombrero_easterhead", Catalogo.SOMBREROS, "", "Easter Island Head", 1200),
            new Pieza("sombrero_eevee_ears", Catalogo.SOMBREROS, "", "Eevee Ears", 1200),
            new Pieza("sombrero_eggcracked", Catalogo.SOMBREROS, "", "Eggcracked", 1200),
            new Pieza("sombrero_egghead", Catalogo.SOMBREROS, "", "Egg Head", 1200),
            new Pieza("sombrero_eggheadspots", Catalogo.SOMBREROS, "", "Eggheadspots", 1200),
            new Pieza("sombrero_eggonhead", Catalogo.SOMBREROS, "", "Egg on Head", 1200),
            new Pieza("sombrero_elfhat", Catalogo.SOMBREROS, "", "Elf Hat", 1200),
            new Pieza("sombrero_explorerhat", Catalogo.SOMBREROS, "", "Explorer Hat", 1200),
            new Pieza("sombrero_eyeholder_beeholder", Catalogo.SOMBREROS, "", "Beeholder", 1200),
            new Pieza("sombrero_eyeholder_dark", Catalogo.SOMBREROS, "", "Dark Eyeholder", 1200),
            new Pieza("sombrero_eyeholder_evil", Catalogo.SOMBREROS, "", "Evil Eyeholder", 1200),
            new Pieza("sombrero_eyeholder_warm", Catalogo.SOMBREROS, "", "Warm Eyeholder", 1200),
            new Pieza("sombrero_eyeholder_xanath", Catalogo.SOMBREROS, "", "Xanath Eyeholder", 1200),
            new Pieza("sombrero_eyepatch", Catalogo.SOMBREROS, "", "Eye Patch", 1200),
            new Pieza("sombrero_fakeblight", Catalogo.SOMBREROS, "", "Blight", 1200),
            new Pieza("sombrero_fakefire", Catalogo.SOMBREROS, "", "Fire", 1200),
            new Pieza("sombrero_farmerbrim", Catalogo.SOMBREROS, "", "Farmer Brim", 1200),
            new Pieza("sombrero_festiveantlers", Catalogo.SOMBREROS, "", "Festive Antlers", 1200),
            new Pieza("sombrero_festiveribbon", Catalogo.SOMBREROS, "", "Festive Ribbon", 1200),
            new Pieza("sombrero_fez", Catalogo.SOMBREROS, "", "Fez", 1200),
            new Pieza("sombrero_finnhood", Catalogo.SOMBREROS, "", "Finn Hood", 1200),
            new Pieza("sombrero_fireworks", Catalogo.SOMBREROS, "", "Fireworks", 1200),
            new Pieza("sombrero_fishing_hat", Catalogo.SOMBREROS, "", "Fishing Hat", 1200),
            new Pieza("sombrero_fishonhead", Catalogo.SOMBREROS, "", "Fish on Head", 1200),
            new Pieza("sombrero_flagjuly", Catalogo.SOMBREROS, "", "Summer Flag", 1200),
            new Pieza("sombrero_flies", Catalogo.SOMBREROS, "", "Flies", 1200),
            new Pieza("sombrero_floatinghearts", Catalogo.SOMBREROS, "", "Floating Hearts", 1200),
            new Pieza("sombrero_floatingstar", Catalogo.SOMBREROS, "", "Floating Star", 1200),
            new Pieza("sombrero_flowercrown", Catalogo.SOMBREROS, "", "Flower Crown", 1200),
            new Pieza("sombrero_floweronhead", Catalogo.SOMBREROS, "", "Flower Head", 1200),
            new Pieza("sombrero_foxhat", Catalogo.SOMBREROS, "", "Fox Hat", 1200),
            new Pieza("sombrero_fro", Catalogo.SOMBREROS, "", "Fro", 1200),
            new Pieza("sombrero_fronthorns", Catalogo.SOMBREROS, "", "Fronthorns", 1200),
            new Pieza("sombrero_frozenhead", Catalogo.SOMBREROS, "", "Frozen Head", 1200),
            new Pieza("sombrero_fulldiamondhelm", Catalogo.SOMBREROS, "", "Fulldiamondhelm", 1200),
            new Pieza("sombrero_fullgoldhelm", Catalogo.SOMBREROS, "", "Fullgoldhelm", 1200),
            new Pieza("sombrero_fullironhelm", Catalogo.SOMBREROS, "", "Armor Helm", 1200),
            new Pieza("sombrero_fullsteelhelm", Catalogo.SOMBREROS, "", "Fullsteelhelm", 1200),
            new Pieza("sombrero_ghostmask", Catalogo.SOMBREROS, "", "Ghost Head", 1200),
            new Pieza("sombrero_gnome", Catalogo.SOMBREROS, "", "Gnome Hat", 1200),
            new Pieza("sombrero_gnome_clover_wig", Catalogo.SOMBREROS, "", "Gnome Disguise", 1200),
            new Pieza("sombrero_gnome_clover_wig_glasses", Catalogo.SOMBREROS, "", "Gnome clover wig glasses", 1200),
            new Pieza("sombrero_goggles", Catalogo.SOMBREROS, "", "Goggles", 1200),
            new Pieza("sombrero_goomyhat", Catalogo.SOMBREROS, "", "Goomyhat", 1200),
            new Pieza("sombrero_goomyhat_shiny", Catalogo.SOMBREROS, "", "Goomyhat shiny", 1200),
            new Pieza("sombrero_grandmadisguise", Catalogo.SOMBREROS, "", "Grandma Disguise", 1200),
            new Pieza("sombrero_greaser", Catalogo.SOMBREROS, "", "Greaser", 1200),
            new Pieza("sombrero_greenbirb", Catalogo.SOMBREROS, "", "Green Birb", 1200),
            new Pieza("sombrero_greenstache", Catalogo.SOMBREROS, "", "Greenstache", 1200),
            new Pieza("sombrero_greyfoxhat", Catalogo.SOMBREROS, "", "Greyfoxhat", 1200),
            new Pieza("sombrero_grinchhat", Catalogo.SOMBREROS, "", "Grinch Mask", 1200),
            new Pieza("sombrero_gwynnza", Catalogo.SOMBREROS, "", "Gwynnza", 1200),
            new Pieza("sombrero_halo", Catalogo.SOMBREROS, "", "Halo", 1200),
            new Pieza("sombrero_hat_of_discipline", Catalogo.SOMBREROS, "", "Hat of Discipline", 1200),
            new Pieza("sombrero_headbolts", Catalogo.SOMBREROS, "", "Head Bolts", 1200),
            new Pieza("sombrero_headphonesblue", Catalogo.SOMBREROS, "", "Headphones", 1200),
            new Pieza("sombrero_headphonespink", Catalogo.SOMBREROS, "", "Headphonespink", 1200),
            new Pieza("sombrero_headphonesred", Catalogo.SOMBREROS, "", "Headphonesred", 1200),
            new Pieza("sombrero_headphonesreggae", Catalogo.SOMBREROS, "", "Headphonesreggae", 1200),
            new Pieza("sombrero_headshot", Catalogo.SOMBREROS, "", "Headshot", 1200),
            new Pieza("sombrero_hockeymask", Catalogo.SOMBREROS, "", "Hockey Mask", 1200),
            new Pieza("sombrero_holyhead", Catalogo.SOMBREROS, "", "Holy Head", 1200),
            new Pieza("sombrero_hoppiphat", Catalogo.SOMBREROS, "", "Hoppiphat", 1200),
            new Pieza("sombrero_horsemask", Catalogo.SOMBREROS, "", "Horse Head", 1200),
            new Pieza("sombrero_hosthat", Catalogo.SOMBREROS, "", "Host", 1200),
            new Pieza("sombrero_icedragonskull", Catalogo.SOMBREROS, "", "Ice Dragon Skull", 1200),
            new Pieza("sombrero_jackohat", Catalogo.SOMBREROS, "", "Jack-o-Lantern Hat", 1200),
            new Pieza("sombrero_jesterhat", Catalogo.SOMBREROS, "", "Jester", 1200),
            new Pieza("sombrero_julydouble", Catalogo.SOMBREROS, "", "Summer Gear", 1200),
            new Pieza("sombrero_julysunglasses", Catalogo.SOMBREROS, "", "Julysunglasses", 1200),
            new Pieza("sombrero_julytophat", Catalogo.SOMBREROS, "", "Julytophat", 1200),
            new Pieza("sombrero_kirbymouthful", Catalogo.SOMBREROS, "", "Mouthful", 1200),
            new Pieza("sombrero_ladybug_on_head", Catalogo.SOMBREROS, "", "Ladybug Friend", 1200),
            new Pieza("sombrero_largehorns", Catalogo.SOMBREROS, "", "Large Horns", 1200),
            new Pieza("sombrero_lightning_eyes", Catalogo.SOMBREROS, "", "Lightning Eyes", 1200),
            new Pieza("sombrero_lil_bows", Catalogo.SOMBREROS, "", "Lil' Bows", 1200),
            new Pieza("sombrero_lil_termagant", Catalogo.SOMBREROS, "", "Lil' Termagant", 1200),
            new Pieza("sombrero_lilbow", Catalogo.SOMBREROS, "", "Lil' Bow", 1200),
            new Pieza("sombrero_lilie_hat", Catalogo.SOMBREROS, "", "Lilie hat", 1200),
            new Pieza("sombrero_longfoxears", Catalogo.SOMBREROS, "", "Long Fox Ears", 1200),
            new Pieza("sombrero_madscientist", Catalogo.SOMBREROS, "", "Wily Head", 1200),
            new Pieza("sombrero_magikarp", Catalogo.SOMBREROS, "", "Magikarp", 1200),
            new Pieza("sombrero_magnemitehat", Catalogo.SOMBREROS, "", "Magnemitehat", 1200),
            new Pieza("sombrero_magnemitehat_shiny", Catalogo.SOMBREROS, "", "Magnemitehat shiny", 1200),
            new Pieza("sombrero_medusa", Catalogo.SOMBREROS, "", "Medusa", 1200),
            new Pieza("sombrero_megamanhat", Catalogo.SOMBREROS, "", "Megaman Head", 1200),
            new Pieza("sombrero_meowthface", Catalogo.SOMBREROS, "", "Meowthface", 1200),
            new Pieza("sombrero_meowthface_alola", Catalogo.SOMBREROS, "", "Meowthface alola", 1200),
            new Pieza("sombrero_meowthface_galarian", Catalogo.SOMBREROS, "", "Meowthface galarian", 1200),
            new Pieza("sombrero_milady_doll", Catalogo.SOMBREROS, "", "Milady Doll", 1200),
            new Pieza("sombrero_mimic_head", Catalogo.SOMBREROS, "", "Mimic", 1200),
            new Pieza("sombrero_mimic_head_dark", Catalogo.SOMBREROS, "", "Dark Mimic", 1200),
            new Pieza("sombrero_mimic_head_gold", Catalogo.SOMBREROS, "", "Gold Mimic", 1200),
            new Pieza("sombrero_mindflayer", Catalogo.SOMBREROS, "", "Mindflayer", 1200),
            new Pieza("sombrero_mindflayer_alhoon", Catalogo.SOMBREROS, "", "Alhoon", 1200),
            new Pieza("sombrero_minerhat", Catalogo.SOMBREROS, "", "Minerhat", 1200),
            new Pieza("sombrero_mistletoe", Catalogo.SOMBREROS, "", "Mistletoe", 1200),
            new Pieza("sombrero_mohawk", Catalogo.SOMBREROS, "", "Mohawk", 1200),
            new Pieza("sombrero_monkeyking", Catalogo.SOMBREROS, "", "Monkey King", 1200),
            new Pieza("sombrero_monocle", Catalogo.SOMBREROS, "", "Monocle", 1200),
            new Pieza("sombrero_moreeyes", Catalogo.SOMBREROS, "", "Eye Head", 1200),
            new Pieza("sombrero_morelullshroom", Catalogo.SOMBREROS, "", "Morelullshroom", 1200),
            new Pieza("sombrero_morelullshroom_shiny", Catalogo.SOMBREROS, "", "Morelullshroom shiny", 1200),
            new Pieza("sombrero_murdered", Catalogo.SOMBREROS, "", "Murdered", 1200),
            new Pieza("sombrero_nekoears", Catalogo.SOMBREROS, "", "Neko Ears", 1200),
            new Pieza("sombrero_nickit_ears", Catalogo.SOMBREROS, "", "Nickit ears", 1200),
            new Pieza("sombrero_nickit_ears_shiny", Catalogo.SOMBREROS, "", "Nickit ears shiny", 1200),
            new Pieza("sombrero_nyan_doll", Catalogo.SOMBREROS, "", "Nyan Doll", 1200),
            new Pieza("sombrero_octodad", Catalogo.SOMBREROS, "", "Octodad", 1200),
            new Pieza("sombrero_orange_hat", Catalogo.SOMBREROS, "", "Orange Hat", 1200),
            new Pieza("sombrero_palmtree", Catalogo.SOMBREROS, "", "Palm Tree", 1200),
            new Pieza("sombrero_paperbag", Catalogo.SOMBREROS, "", "Paper Bag", 1200),
            new Pieza("sombrero_parasshroom", Catalogo.SOMBREROS, "", "Parasshroom", 1200),
            new Pieza("sombrero_partyhat", Catalogo.SOMBREROS, "", "Party Hat", 1200),
            new Pieza("sombrero_paypay", Catalogo.SOMBREROS, "", "Paypay", 1200),
            new Pieza("sombrero_peepo", Catalogo.SOMBREROS, "", "Peepo", 1200),
            new Pieza("sombrero_penguinbaby", Catalogo.SOMBREROS, "", "Baby Penguin", 1200),
            new Pieza("sombrero_penguinhat", Catalogo.SOMBREROS, "", "Penguin Hat", 1200),
            new Pieza("sombrero_peppino", Catalogo.SOMBREROS, "", "Peppino", 1200),
            new Pieza("sombrero_pighead", Catalogo.SOMBREROS, "", "Pig Head", 1200),
            new Pieza("sombrero_pika_ears", Catalogo.SOMBREROS, "", "Pika Ears", 1200),
            new Pieza("sombrero_pinhead", Catalogo.SOMBREROS, "", "Pin Head", 1200),
            new Pieza("sombrero_plaguedoctor", Catalogo.SOMBREROS, "", "Plague Doctor", 1200),
            new Pieza("sombrero_pog", Catalogo.SOMBREROS, "", "Poggers", 1200),
            new Pieza("sombrero_pohatoe", Catalogo.SOMBREROS, "", "Pohatoe", 1200),
            new Pieza("sombrero_policebucket", Catalogo.SOMBREROS, "", "Police Bucket", 1200),
            new Pieza("sombrero_policesiren", Catalogo.SOMBREROS, "", "Siren", 1200),
            new Pieza("sombrero_pom_moog", Catalogo.SOMBREROS, "", "Pom-Moog", 1200),
            new Pieza("sombrero_poofballhat", Catalogo.SOMBREROS, "", "Poofball", 1200),
            new Pieza("sombrero_poofballrgb", Catalogo.SOMBREROS, "", "RGB Poofball", 1200),
            new Pieza("sombrero_popehat", Catalogo.SOMBREROS, "", "Pope Hat", 1200),
            new Pieza("sombrero_potionhead", Catalogo.SOMBREROS, "", "Potion Head", 1200),
            new Pieza("sombrero_presentsstack", Catalogo.SOMBREROS, "", "Presents", 1200),
            new Pieza("sombrero_propelhat", Catalogo.SOMBREROS, "", "Propeller", 1200),
            new Pieza("sombrero_psycap", Catalogo.SOMBREROS, "", "Psycap", 1200),
            new Pieza("sombrero_psycap_shiny", Catalogo.SOMBREROS, "", "Psycap shiny", 1200),
            new Pieza("sombrero_puchiko", Catalogo.SOMBREROS, "", "Puchiko's Hat", 1200),
            new Pieza("sombrero_questbook", Catalogo.SOMBREROS, "", "Questbook Hat", 1200),
            new Pieza("sombrero_rabbitears", Catalogo.SOMBREROS, "", "Bunny Ears", 1200),
            new Pieza("sombrero_rabbitonhead", Catalogo.SOMBREROS, "", "Bunny on Head", 1200),
            new Pieza("sombrero_rabi_en_rose", Catalogo.SOMBREROS, "", "Rabi~en~Rose's Hat", 1200),
            new Pieza("sombrero_rabi_en_rose_wig", Catalogo.SOMBREROS, "", "Rabi en rose wig", 1200),
            new Pieza("sombrero_rainboworbiters", Catalogo.SOMBREROS, "", "Rainbow Orbiters", 1200),
            new Pieza("sombrero_raincloud", Catalogo.SOMBREROS, "", "Raincloud", 1200),
            new Pieza("sombrero_ranahat", Catalogo.SOMBREROS, "", "Rana Cap", 1200),
            new Pieza("sombrero_redeyes", Catalogo.SOMBREROS, "", "Red Eyes", 1200),
            new Pieza("sombrero_rednose", Catalogo.SOMBREROS, "", "Red Nose", 1200),
            new Pieza("sombrero_redshroomcap", Catalogo.SOMBREROS, "", "Redshroomcap", 1200),
            new Pieza("sombrero_redstache", Catalogo.SOMBREROS, "", "Plumber Stache", 1200),
            new Pieza("sombrero_rgbbigribbon", Catalogo.SOMBREROS, "", "RGB Big Ribbon", 1200),
            new Pieza("sombrero_rgbbowler", Catalogo.SOMBREROS, "", "RGB Bowler Cap", 1200),
            new Pieza("sombrero_rgbdragonskull", Catalogo.SOMBREROS, "", "RGB Dragon Skull", 1200),
            new Pieza("sombrero_rgbdrinkinhat", Catalogo.SOMBREROS, "", "RGB Drinking Hat", 1200),
            new Pieza("sombrero_rgbeasterhead", Catalogo.SOMBREROS, "", "RGB Easter Island Head", 1200),
            new Pieza("sombrero_rgbfullhelm", Catalogo.SOMBREROS, "", "RGB Armor Helm", 1200),
            new Pieza("sombrero_rgbpartyhat", Catalogo.SOMBREROS, "", "RGB Party Hat", 1200),
            new Pieza("sombrero_rgbsmallbowler", Catalogo.SOMBREROS, "", "RGB Small Bowler Cap", 1200),
            new Pieza("sombrero_rgbsunglasses", Catalogo.SOMBREROS, "", "RGB Sunglasses", 1200),
            new Pieza("sombrero_rgbtoptophathat", Catalogo.SOMBREROS, "", "RGB Toptop Hathat", 1200),
            new Pieza("sombrero_rgbushanka", Catalogo.SOMBREROS, "", "RGB Ushanka", 1200),
            new Pieza("sombrero_right_hand_hat", Catalogo.SOMBREROS, "", "Right Hand", 1200),
            new Pieza("sombrero_right_hand_hat_cyborg", Catalogo.SOMBREROS, "", "Right hand hat cyborg", 1200),
            new Pieza("sombrero_rimglasses", Catalogo.SOMBREROS, "", "Rimglasses", 1200),
            new Pieza("sombrero_rock", Catalogo.SOMBREROS, "", "Rock Eye", 1200),
            new Pieza("sombrero_round_purple_wig", Catalogo.SOMBREROS, "", "Purple Wig", 1200),
            new Pieza("sombrero_round_purple_wig_glasses", Catalogo.SOMBREROS, "", "Round purple wig glasses", 1200),
            new Pieza("sombrero_round_red_wig", Catalogo.SOMBREROS, "", "Red Wig", 1200),
            new Pieza("sombrero_round_red_wig_glasses", Catalogo.SOMBREROS, "", "Round red wig glasses", 1200),
            new Pieza("sombrero_rubbernipple", Catalogo.SOMBREROS, "", "Baby Bottle Head", 1200),
            new Pieza("sombrero_sandcastle", Catalogo.SOMBREROS, "", "Sand Castle", 1200),
            new Pieza("sombrero_santaclaus", Catalogo.SOMBREROS, "", "Santa Claus", 1200),
            new Pieza("sombrero_santahat", Catalogo.SOMBREROS, "", "Santahat", 1200),
            new Pieza("sombrero_sausage", Catalogo.SOMBREROS, "", "Sausage", 1200),
            new Pieza("sombrero_scorbunny", Catalogo.SOMBREROS, "", "Scorbunny", 1200),
            new Pieza("sombrero_scorbunny_shiny", Catalogo.SOMBREROS, "", "Scorbunny shiny", 1200),
            new Pieza("sombrero_scouter", Catalogo.SOMBREROS, "", "Scouter", 1200),
            new Pieza("sombrero_seaweedhat", Catalogo.SOMBREROS, "", "Seaweed Hat", 1200),
            new Pieza("sombrero_serenajn", Catalogo.SOMBREROS, "", "Serenajn", 1200),
            new Pieza("sombrero_serenaxy", Catalogo.SOMBREROS, "", "Serenaxy", 1200),
            new Pieza("sombrero_shakehat", Catalogo.SOMBREROS, "", "Shake Head", 1200),
            new Pieza("sombrero_sheep", Catalogo.SOMBREROS, "", "Sheep Head", 1200),
            new Pieza("sombrero_shinymagikarp", Catalogo.SOMBREROS, "", "Shinymagikarp", 1200),
            new Pieza("sombrero_shrekears", Catalogo.SOMBREROS, "", "Shrek Ears", 1200),
            new Pieza("sombrero_shroomcap", Catalogo.SOMBREROS, "", "Shroom Cap", 1200),
            new Pieza("sombrero_sidebow", Catalogo.SOMBREROS, "", "Sidebow", 1200),
            new Pieza("sombrero_simsgem", Catalogo.SOMBREROS, "", "Plumbob", 1200),
            new Pieza("sombrero_sleepeyemask", Catalogo.SOMBREROS, "", "Sleep Eye Mask", 1200),
            new Pieza("sombrero_slime_cube_dnd", Catalogo.SOMBREROS, "", "Dungeon Slime Cube", 1200),
            new Pieza("sombrero_slime_head", Catalogo.SOMBREROS, "", "Slime Head", 1200),
            new Pieza("sombrero_smokingpipe", Catalogo.SOMBREROS, "", "Smoking Pipe", 1200),
            new Pieza("sombrero_snowmanbaby", Catalogo.SOMBREROS, "", "Baby Snowman", 1200),
            new Pieza("sombrero_sombrero", Catalogo.SOMBREROS, "", "Sombrero", 1200),
            new Pieza("sombrero_sonichood", Catalogo.SOMBREROS, "", "Sonic Head", 1200),
            new Pieza("sombrero_spadesoldier", Catalogo.SOMBREROS, "", "Spade Soldier", 1200),
            new Pieza("sombrero_special", Catalogo.SOMBREROS, "", "The Simple Hat", 1200),
            new Pieza("sombrero_spiderweb", Catalogo.SOMBREROS, "", "Web Head", 1200),
            new Pieza("sombrero_sport_sunglasses", Catalogo.SOMBREROS, "", "Sport Sunglasses", 1200),
            new Pieza("sombrero_springer", Catalogo.SOMBREROS, "", "Springer", 1200),
            new Pieza("sombrero_sprout", Catalogo.SOMBREROS, "", "Sprout", 1200),
            new Pieza("sombrero_spyzombie", Catalogo.SOMBREROS, "", "Spy Zombie", 1200),
            new Pieza("sombrero_stackofeggs", Catalogo.SOMBREROS, "", "Egg Stack", 1200),
            new Pieza("sombrero_staryuclip", Catalogo.SOMBREROS, "", "Staryuclip", 1200),
            new Pieza("sombrero_staryuclip_shiny", Catalogo.SOMBREROS, "", "Staryuclip shiny", 1200),
            new Pieza("sombrero_stinkycheeseman", Catalogo.SOMBREROS, "", "Stinky Cheese Man", 1200),
            new Pieza("sombrero_strawberry_hat", Catalogo.SOMBREROS, "", "Strawberry Hat", 1200),
            new Pieza("sombrero_stress", Catalogo.SOMBREROS, "", "Stress", 1200),
            new Pieza("sombrero_stuck_lollipop", Catalogo.SOMBREROS, "", "Stuck Lollipop", 1200),
            new Pieza("sombrero_summerhat", Catalogo.SOMBREROS, "", "Summer Hat", 1200),
            new Pieza("sombrero_sunglasses", Catalogo.SOMBREROS, "", "Sunglasses", 1200),
            new Pieza("sombrero_sunglassesbig", Catalogo.SOMBREROS, "", "Big Sunglasses", 1200),
            new Pieza("sombrero_supersandhat", Catalogo.SOMBREROS, "", "Saiyan Head", 1200),
            new Pieza("sombrero_swimmer", Catalogo.SOMBREROS, "", "Swimmer Cap", 1200),
            new Pieza("sombrero_sylveonears", Catalogo.SOMBREROS, "", "Sylveonears", 1200),
            new Pieza("sombrero_sylveonears_shiny", Catalogo.SOMBREROS, "", "Sylveonears shiny", 1200),
            new Pieza("sombrero_tanuki_leaf", Catalogo.SOMBREROS, "", "Tanuki Leaf", 1200),
            new Pieza("sombrero_teddy_bear", Catalogo.SOMBREROS, "", "Teddy Bear", 1200),
            new Pieza("sombrero_teddy_bear_bee", Catalogo.SOMBREROS, "", "Teddy bear bee", 1200),
            new Pieza("sombrero_teddy_bear_ken", Catalogo.SOMBREROS, "", "Teddy bear ken", 1200),
            new Pieza("sombrero_teddy_bear_panda", Catalogo.SOMBREROS, "", "Teddy bear panda", 1200),
            new Pieza("sombrero_teddy_bear_rembo", Catalogo.SOMBREROS, "", "Teddy bear rembo", 1200),
            new Pieza("sombrero_teddy_bear_ryu", Catalogo.SOMBREROS, "", "Teddy bear ryu", 1200),
            new Pieza("sombrero_teddy_bear_scary", Catalogo.SOMBREROS, "", "Teddy bear scary", 1200),
            new Pieza("sombrero_the_noise", Catalogo.SOMBREROS, "", "The Noise", 1200),
            new Pieza("sombrero_the_noisier", Catalogo.SOMBREROS, "", "The Noisier", 1200),
            new Pieza("sombrero_thumbnail", Catalogo.SOMBREROS, "", "Youtube Thumbnail", 1200),
            new Pieza("sombrero_tick_on_head", Catalogo.SOMBREROS, "", "Tick Friend", 1200),
            new Pieza("sombrero_tinkerhat", Catalogo.SOMBREROS, "", "Tinker's Helm", 1200),
            new Pieza("sombrero_toast", Catalogo.SOMBREROS, "", "Toast", 1200),
            new Pieza("sombrero_toedscool", Catalogo.SOMBREROS, "", "Toedscool", 1200),
            new Pieza("sombrero_toedscool_shiny", Catalogo.SOMBREROS, "", "Toedscool shiny", 1200),
            new Pieza("sombrero_toilet", Catalogo.SOMBREROS, "", "Toilet Head", 1200),
            new Pieza("sombrero_tomato_splats", Catalogo.SOMBREROS, "", "Tomato Splats", 1200),
            new Pieza("sombrero_topcathat", Catalogo.SOMBREROS, "", "Top Cat Hat", 1200),
            new Pieza("sombrero_tophat", Catalogo.SOMBREROS, "", "Top Hat", 1200),
            new Pieza("sombrero_toptophathat", Catalogo.SOMBREROS, "", "Toptop Hathat", 1200),
            new Pieza("sombrero_toy_story_alien", Catalogo.SOMBREROS, "", "Toy Story Alien", 1200),
            new Pieza("sombrero_traffic_cone", Catalogo.SOMBREROS, "", "Traffic Cone", 1200),
            new Pieza("sombrero_triangleshades", Catalogo.SOMBREROS, "", "Angled Shades", 1200),
            new Pieza("sombrero_tricorne", Catalogo.SOMBREROS, "", "Tricorne", 1200),
            new Pieza("sombrero_tvhead", Catalogo.SOMBREROS, "", "TV Head", 1200),
            new Pieza("sombrero_tvheadrat", Catalogo.SOMBREROS, "", "Tvheadrat", 1200),
            new Pieza("sombrero_tvheadstatic", Catalogo.SOMBREROS, "", "Tvheadstatic", 1200),
            new Pieza("sombrero_twilight_doll", Catalogo.SOMBREROS, "", "Twilight Doll", 1200),
            new Pieza("sombrero_udder_hat", Catalogo.SOMBREROS, "", "Udder Hat", 1200),
            new Pieza("sombrero_umbreoncap", Catalogo.SOMBREROS, "", "Umbreoncap", 1200),
            new Pieza("sombrero_umbreoncap_shiny", Catalogo.SOMBREROS, "", "Umbreoncap shiny", 1200),
            new Pieza("sombrero_unicornhorn", Catalogo.SOMBREROS, "", "Unicorn Horn", 1200),
            new Pieza("sombrero_ushanka", Catalogo.SOMBREROS, "", "Ushanka", 1200),
            new Pieza("sombrero_vikinghat", Catalogo.SOMBREROS, "", "Vikinghat", 1200),
            new Pieza("sombrero_vikinghatbeard", Catalogo.SOMBREROS, "", "Viking Helm", 1200),
            new Pieza("sombrero_villagernose", Catalogo.SOMBREROS, "", "Villager Nose", 1200),
            new Pieza("sombrero_wigglethat", Catalogo.SOMBREROS, "", "Wigglethat", 1200),
            new Pieza("sombrero_wigglethat_shiny", Catalogo.SOMBREROS, "", "Wigglethat shiny", 1200),
            new Pieza("sombrero_winghat", Catalogo.SOMBREROS, "", "Wing Cap", 1200),
            new Pieza("sombrero_worm_hat", Catalogo.SOMBREROS, "", "Worm Hat", 1200),
            new Pieza("sombrero_worms_mine", Catalogo.SOMBREROS, "", "Worm's Mine", 1200),
            new Pieza("sombrero_zigzagwitchhat", Catalogo.SOMBREROS, "", "Witch Hat", 1200),
            new Pieza("sombrero_gorra_poke", Catalogo.SOMBREROS, "", "Gorra Poké Ball", 2000),
            new Pieza("sombrero_gorra_great", Catalogo.SOMBREROS, "", "Gorra Super Ball", 2000),
            new Pieza("sombrero_gorra_ultra", Catalogo.SOMBREROS, "", "Gorra Ultra Ball", 2000),
            new Pieza("sombrero_gorra_master", Catalogo.SOMBREROS, "", "Gorra Master Ball", 3500),
            new Pieza("sombrero_gorra_premier", Catalogo.SOMBREROS, "", "Gorra Premier Ball", 2000),
            new Pieza("sombrero_gorra_dusk", Catalogo.SOMBREROS, "", "Gorra Ocaso", 2000),
            new Pieza("sombrero_gorra_heal", Catalogo.SOMBREROS, "", "Gorra Sanadora", 2000),
            new Pieza("sombrero_gorra_net", Catalogo.SOMBREROS, "", "Gorra Malla", 2000),
            new Pieza("sombrero_gorra_dive", Catalogo.SOMBREROS, "", "Gorra Buceo", 2000),
            new Pieza("sombrero_gorra_quick", Catalogo.SOMBREROS, "", "Gorra Veloz", 2000),
            new Pieza("sombrero_gorra_luxury", Catalogo.SOMBREROS, "", "Gorra Lujo", 3500),
            new Pieza("sombrero_gorra_level", Catalogo.SOMBREROS, "", "Gorra Nivel", 2000),
            new Pieza("sombrero_gorra_friend", Catalogo.SOMBREROS, "", "Gorra Amiga", 2000),
            new Pieza("sombrero_gorra_love", Catalogo.SOMBREROS, "", "Gorra Amor", 2000),
            new Pieza("sombrero_gorra_moon", Catalogo.SOMBREROS, "", "Gorra Lunar", 2000),
            new Pieza("sombrero_gorra_timer", Catalogo.SOMBREROS, "", "Gorra Turno", 2000),
            new Pieza("sombrero_gorra_repeat", Catalogo.SOMBREROS, "", "Gorra Acopio", 2000),
            new Pieza("sombrero_gorra_nest", Catalogo.SOMBREROS, "", "Gorra Nido", 2000),
            new Pieza("sombrero_gorra_beast", Catalogo.SOMBREROS, "", "Gorra Ente", 3500),
            new Pieza("sombrero_gorra_cherish", Catalogo.SOMBREROS, "", "Gorra Gloria", 3500)
    );
}
