"""Build the independent PokeReport portal. No checkout or payment logic is replaced."""
from pathlib import Path
import json, html, shutil, hashlib

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'dist'
OUT.mkdir(exist_ok=True)
shutil.copytree(ROOT / 'public', OUT, dirs_exist_ok=True)
ARTICLES = json.loads((ROOT / 'content.json').read_text(encoding='utf-8'))
VERSION = hashlib.sha256((ROOT/'public/portal-assets/portal.css').read_bytes() + (ROOT/'public/portal-assets/portal.js').read_bytes()).hexdigest()[:12]

def icon(name):
    paths = {'arrow':'M7 17 17 7M7 7h10v10','download':'M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5', 'book':'M12 6c-3-2-7-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V5c-2-1-6-1-9 1v15','spark':'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z','copy':'M9 9h12v12H9ZM3 15V3h12','menu':'M3 6h18M3 12h18M3 18h18','search':'M21 21l-6-6M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0','heart':'M12 21S2 15 2 8a5 5 0 0 1 10-2 5 5 0 0 1 10 2c0 7-10 13-10 13Z'}
    return f'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="{paths.get(name, paths["spark"])}"/></svg>'

def button(text, href, kind='primary', sym='arrow'):
    return f'<a class="btn {kind}" href="{href}">{icon(sym)}{text}</a>'

def card(article):
    return f'<a class="guide-card" href="/wiki/{article["slug"]}/"><span class="card-icon">{icon(article["icon"])}</span><span class="tag">{article["category"]}</span><h3>{article["title"]}</h3><p>{article["summary"]}</p><span class="card-link">Leer guía {icon("arrow")}</span></a>'

def layout(title, desc, content, active='inicio', path='/'):
    nav = ''.join(f'<a href="{url}" {"aria-current=page" if key==active else ""}>{label}</a>' for key,label,url in [('inicio','Inicio','/'),('jugar','Cómo jugar','/jugar/'),('wiki','Wiki','/wiki/'),('tienda','Tienda','/tienda/')])
    return f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} · PokeReport Network</title><meta name="description" content="{html.escape(desc)}"><meta name="theme-color" content="#080b14"><link rel="canonical" href="https://pokereport.online{path}"><meta property="og:title" content="{html.escape(title)} · PokeReport Network"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:image" content="https://pokereport.online/portal-assets/ciudadela.webp"><link rel="icon" href="/portal-assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/portal-assets/portal.css?v=1"><script src="/portal-assets/portal.js?v=1" defer></script></head><body><a class="skip" href="#main">Saltar al contenido</a><header class="header"><a class="brand" href="/" aria-label="PokeReport, inicio"><span class="brand-orbit">P</span><span>POKEREPORT<small>NETWORK · LUNA ETERNAL</small></span></a><nav class="desktop-nav" aria-label="Principal">{nav}</nav><a class="nav-discord" href="https://discord.gg/JsUTQWRH8H" target="_blank" rel="noopener">Comunidad {icon('arrow')}</a><a class="nav-play" href="/jugar/">Jugar ahora {icon('arrow')}</a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav" aria-label="Abrir navegación">{icon('menu')}</button></header><nav id="mobile-nav" class="mobile-nav" hidden aria-label="Navegación móvil">{nav}<a href="https://discord.gg/JsUTQWRH8H">Discord</a></nav><main id="main">{content}</main><footer class="footer"><div class="footer-top"><a class="brand" href="/"><span class="brand-orbit">P</span><span>POKEREPORT<small>TU HISTORIA EMPIEZA AQUÍ.</small></span></a><div><a href="/jugar/">Descargar launcher</a><a href="/wiki/">Explorar wiki</a><a href="/tienda/">Tienda oficial</a><a href="https://discord.gg/JsUTQWRH8H" target="_blank" rel="noopener">Discord</a></div></div><div class="footer-bottom"><span>© 2026 PokeReport Network · Luna Eternal</span><span>Comunidad independiente. Minecraft y Pokémon pertenecen a sus respectivos titulares.</span></div></footer><div class="toast" role="status" aria-live="polite"></div></body></html>'''

def write(path, text):
    file = OUT / path / 'index.html'
    file.parent.mkdir(parents=True, exist_ok=True)
    file.write_text(text.replace('?v=1', '?v='+VERSION), encoding='utf-8')

hero = f'''<section class="hero"><div class="hero-bg" aria-hidden="true"></div><div class="hero-content"><div class="eyebrow"><span class="light-dot"></span> UN MUNDO, MIL HISTORIAS</div><img class="hero-logo" src="/portal-assets/logo.webp" alt="PokeReport Network" width="780" height="195"><h1>Tu próxima aventura<br>empieza bajo <em>la luna.</em></h1><p>Encuentra a tu primer compañero. Recorre la Ciudadela.<br class="desktop-only"> Y escribe tu propia historia en nuestro mundo de Cobblemon.</p><div class="hero-actions">{button('Empieza tu aventura','/jugar/','primary','download')}{button('Explorar la wiki','/wiki/','secondary','book')}</div><div class="hero-meta"><span>MINECRAFT JAVA 1.21.1</span><span>COBBLEMON 1.8.0</span><span>COMUNIDAD EN ESPAÑOL</span></div></div><div class="world-caption"><span class="caption-marker"></span><div>LA CIUDADELA<small>Un lugar al que siempre volver.</small></div></div><a class="scroll-cue" href="#descubre">DESCUBRE LUNA ETERNAL <span>↓</span></a></section>
<section class="quick-links" aria-label="Accesos rápidos"><a href="/jugar/"><span class="quick-icon">{icon('download')}</span><span><small>TU PRIMER PASO</small><strong>Launcher oficial</strong></span>{icon('arrow')}</a><a href="/wiki/"><span class="quick-icon">{icon('book')}</span><span><small>TODO A TU ALCANCE</small><strong>La guía del entrenador</strong></span>{icon('arrow')}</a><a href="/tienda/"><span class="quick-icon">{icon('spark')}</span><span><small>APOYA TU MUNDO</small><strong>Tienda PokeReport</strong></span>{icon('arrow')}</a></section>
<section class="section" id="descubre"><div class="section-heading"><div><span class="eyebrow">MUCHO MÁS QUE UN DESTINO</span><h2>Un mundo para quedarse.</h2></div><p>Explora a tu ritmo. Construye tu equipo.<br>Encuentra tu lugar entre otros entrenadores.</p></div><div class="world-grid"><a class="world-card world-city" href="/wiki/mundos/"><div><span class="tag">EXPLORACIÓN</span><h3>Todos los caminos<br>llevan a la Ciudadela.</h3><p>Tu punto de encuentro, servicios y nuevas aventuras.</p><span class="card-link">Descubre los mundos {icon('arrow')}</span></div></a><div class="world-stack"><a class="feature-card" href="/wiki/gimnasios/"><span class="feature-number">01 / SUPÉRATE</span><h3>Tu equipo. Tu desafío.</h3><p>Prepárate para los gimnasios y la Torre de Batalla.</p><span class="card-link">Guía de combate {icon('arrow')}</span></a><a class="feature-card violet" href="/wiki/pokepad/"><span class="feature-number">02 / CONÉCTATE</span><h3>Tu aventura, en un PokéPad.</h3><p>Viajes, misiones, mercado y sistemas del servidor, reunidos en el juego.</p><span class="card-link">Conoce el PokéPad {icon('arrow')}</span></a></div></div></section>
<section class="start-section" id="como-empezar"><div class="section"><div class="section-heading"><div><span class="eyebrow">LA AVENTURA EMPIEZA CONTIGO</span><h2>De aquí a tu primer compañero.</h2></div>{button('Ver la guía completa','/jugar/','secondary')}</div><div class="steps"><article><span>01</span><h3>Descarga el launcher</h3><p>Instala PokeReport en Windows. El launcher prepara y actualiza tu modpack.</p><a href="/jugar/">Descargar {icon('arrow')}</a></article><article><span>02</span><h3>Entra a PokeReport</h3><p>Abre Minecraft desde el launcher y pulsa POKEREPORT NETWORK. Identifícate en el lobby.</p><a href="/wiki/primeros-pasos/">Primer acceso {icon('arrow')}</a></article><article><span>03</span><h3>Encuentra a tu compañero</h3><p>Cruza con el guardián a la Ciudadela y visita a Oak para elegir tu inicial.</p><a href="/wiki/primeros-pasos/#tu-inicial">Comienza tu historia {icon('arrow')}</a></article></div><div class="server-address"><div><span class="light-dot"></span><span>EL ACCESO OFICIAL<small>El launcher ya conecta con nuestro servidor.</small></span></div><button class="copy-ip" data-copy="play.pokereport.online">play.pokereport.online {icon('copy')}</button></div></div></section>
<section class="section"><div class="section-heading"><div><span class="eyebrow">CONOCER ES PARTE DE LA AVENTURA</span><h2>Tu siguiente descubrimiento.</h2></div><a class="text-link" href="/wiki/">Toda la wiki {icon('arrow')}</a></div><div class="guide-grid">{''.join(card(a) for a in ARTICLES[:3])}</div></section>
<section class="memorial section"><span class="memorial-orbit">{icon('heart')}</span><div><span class="eyebrow">HAY COMPAÑEROS QUE SON PARA SIEMPRE</span><h2>Una pequeña luz llamada Lunita.</h2><p>El cariño que dejó sigue brillando en nuestro mundo.<br>Conoce a la compañera que vive en el corazón de PokeReport.</p><a class="text-link" href="/wiki/lunita/">Su historia {icon('arrow')}</a></div></section>
<section class="community section"><span class="eyebrow">NOS VEMOS AL OTRO LADO</span><h2>Lo mejor de la aventura<br>es con quién la compartes.</h2><p>Encuentra otros entrenadores, sigue las novedades<br>y pide ayuda al equipo en nuestro Discord.</p>{button('Únete a la comunidad','https://discord.gg/JsUTQWRH8H','primary')}</section>'''
write('', layout('Tu aventura comienza aquí','Descarga el launcher oficial, explora la wiki y entra al mundo Cobblemon de PokeReport Network.',hero))

download = f'''<section class="page-intro section"><span class="eyebrow">BIENVENIDO A TU NUEVA AVENTURA</span><h1>Tu mundo está<br>a <em>un primer paso.</em></h1><p>Descarga el launcher oficial de PokeReport.<br>Nosotros preparamos el modpack. Tú eliges tu historia.</p></section><section class="section download-layout"><article class="download-card"><span class="tag">LAUNCHER OFICIAL · WINDOWS 64 BITS</span><div class="download-emblem">P<span>✦</span></div><h2>PokeReport Network</h2><p>Launcher 0.2.3 · Instalador para Windows</p>{button('Descargar para Windows','/descargas/PokeReport-Launcher-0.2.3.exe','primary','download')}<small>Descarga directa desde pokereport.online · 27,2 MiB</small><div class="download-includes"><span>✓ Modpack oficial</span><span>✓ Actualizaciones del pack</span><span>✓ Acceso a PokeReport</span></div></article><div class="install-steps"><article><span>01</span><div><h2>Instala y abre el launcher</h2><p>Ejecuta el instalador descargado. Utiliza el launcher oficial para mantener los archivos del juego al día.</p></div></article><article><span>02</span><div><h2>Prepara tu perfil y pulsa Jugar</h2><p>Selecciona tu perfil de jugador y deja que termine la preparación del pack antes de abrir Minecraft.</p></div></article><article><span>03</span><div><h2>Entra desde POKEREPORT NETWORK</h2><p>Identifícate en el lobby y habla con el guardián para entrar a la Ciudadela. Oak te espera con tu primer compañero.</p><a class="text-link" href="/wiki/primeros-pasos/">Guía de tu primer acceso {icon('arrow')}</a></div></article></div></section><section class="section faq"><span class="eyebrow">ANTES DE EMPEZAR</span><h2>Un poco de ayuda nunca sobra.</h2><details><summary>¿Necesito descargar los mods por separado?</summary><p>No. El launcher prepara el modpack oficial y sincroniza sus actualizaciones antes de jugar.</p></details><details><summary>¿Qué versión de Minecraft utiliza?</summary><p>Minecraft Java 1.21.1 con Cobblemon 1.8.0. Usa el perfil preparado por el launcher para evitar diferencias con el servidor.</p></details><details><summary>¿Puedo instalarlo en macOS o Linux?</summary><p>El instalador publicado actualmente es para Windows de 64 bits. Consulta con el equipo en Discord si utilizas otro sistema.</p></details><details><summary>¿Qué hago si Minecraft se cierra o no puedo entrar?</summary><p>Cierra Minecraft por completo y vuelve a abrir el launcher. Consulta la guía de soporte y comparte el registro del error con el equipo; no publiques contraseñas ni datos de acceso.</p><a href="/wiki/soporte/">Abrir la guía de soporte →</a></details></section>'''
write('jugar', layout('Descarga el launcher oficial','Descarga directa del launcher PokeReport para Windows. Instalación, primer acceso y ayuda.',download,'jugar','/jugar/'))

def sidebar(current=''):
    groups = dict.fromkeys(a['category'] for a in ARTICLES)
    content = ''
    for group in groups:
        content += f'<div class="sidebar-group"><h2>{group}</h2>'
        content += ''.join(f'<a href="/wiki/{a["slug"]}/" {"aria-current=page" if a["slug"]==current else ""}>{icon(a["icon"])}{a["title"]}</a>' for a in ARTICLES if a['category']==group)
        content += '</div>'
    return f'<aside class="wiki-sidebar"><a class="wiki-label" href="/wiki/">{icon("book")} WIKI POKEREPORT</a><button class="wiki-toggle" aria-expanded="false">Índice de guías {icon("menu")}</button><div class="wiki-links">{content}<a class="sidebar-help" href="https://discord.gg/JsUTQWRH8H" target="_blank" rel="noopener">¿Necesitas ayuda? <span>Habla con la comunidad ↗</span></a></div></aside>'

search = f'<div class="wiki-search">{icon("search")}<input type="search" id="wiki-search" placeholder="Busca una guía: crianza, monedas, primer acceso…" aria-label="Buscar en la wiki" autocomplete="off"><kbd>/</kbd><div id="search-results" hidden role="region" aria-label="Resultados de búsqueda"></div></div>'
wiki_home = f'<div class="wiki-layout">{sidebar()}<div class="wiki-main">{search}<div class="wiki-welcome"><span class="eyebrow">TU COMPAÑERA DE AVENTURAS</span><h1>Todo un mundo.<br><em>Una guía para descubrirlo.</em></h1><p>El conocimiento también se entrena. Encuentra tu próximo paso en Luna Eternal.</p><a class="btn primary" href="/wiki/primeros-pasos/">Empieza por aquí {icon("arrow")}</a></div><div class="wiki-category-heading"><h2>Explora la wiki</h2><span>{len(ARTICLES)} guías · En español</span></div><div class="wiki-guide-grid">{"".join(card(a) for a in ARTICLES)}</div></div></div>'
write('wiki',layout('Wiki oficial','Guías de PokeReport: primeros pasos, PokéPad, mundos, economía, crianza y más.',wiki_home,'wiki','/wiki/'))
for a in ARTICLES:
    sections = ''.join(f'<section id="{s["id"]}" class="article-section"><h2>{s["title"]}</h2>{s["body"]}</section>' for s in a['sections'])
    toc = ''.join(f'<a href="#{s["id"]}">{s["title"]}</a>' for s in a['sections'])
    related = ''.join(f'<a href="/wiki/{r}/">{next(x["title"] for x in ARTICLES if x["slug"]==r)} {icon("arrow")}</a>' for r in a['related'])
    body = f'<div class="wiki-layout">{sidebar(a["slug"])}<div class="wiki-main">{search}<div class="article-layout"><article class="wiki-article"><div class="breadcrumb"><a href="/wiki/">Wiki</a><span>/</span>{a["category"]}</div><span class="eyebrow">{a["category"]}</span><h1>{a["title"]}</h1><p class="article-summary">{a["summary"]}</p><div class="article-meta">GUÍA OFICIAL <span>•</span> ACTUALIZADA EL 2 OCT 2026</div>{sections}<div class="article-related"><span class="eyebrow">CONTINÚA EXPLORANDO</span>{related}</div></article><aside class="article-toc"><span>EN ESTA GUÍA</span>{toc}<a href="https://discord.gg/JsUTQWRH8H" target="_blank" rel="noopener">Pregúntanos en Discord ↗</a></aside></div></div></div>'
    write('wiki/'+a['slug'],layout(a['title'],a['summary'],body,'wiki','/wiki/'+a['slug']+'/'))
(OUT/'portal-assets/search.json').write_text(json.dumps([{k:a[k] for k in ['slug','title','summary','category']} for a in ARTICLES],ensure_ascii=False),encoding='utf-8')
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://pokereport.online/sitemap.xml\n')
urls = ['/', '/jugar/', '/wiki/'] + ['/wiki/'+a['slug']+'/' for a in ARTICLES]
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://pokereport.online'+u+'</loc></url>' for u in urls)+'</urlset>')
print(f'Built {len(urls)} pages; original store remains independently deployed at /tienda/.')
(OUT/'404.html').write_text(layout('Un camino por descubrir','Esta página no existe. Vuelve a PokeReport o consulta nuestra wiki.', '<section class="section page-intro"><span class="eyebrow">404 · FUERA DEL MAPA</span><h1>Este camino aún<br>no lleva a ninguna parte.</h1><p>Vuelve a la Ciudadela digital y encuentra tu próximo destino.</p>'+button('Volver al inicio','/')+button('Explorar la wiki','/wiki/','secondary')+'</section>'),encoding='utf-8')
